version: '3'

services:
  mariadb:
    ports:
      - 3306:3306

  php-fpm:
    volumes:
      - ./src:/var/www/magento

  nginx:
    volumes:
      - ./src:/var/www/magento:ro
    ports:
      - 80:80

  mailcatcher:
    ports:
      - 1080:1080
